default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
  DIRS_RESOURCES:
    - config
    - shop/mainapp/templates/
  DIRS_SOURCES:
    - shop
  DIRS_TEMPLATES:
  HOST: ""
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  REQUEST_TTL: 0
  SECRET_KEY: ""
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  TEST_BROWSER: ""
  TEST_BROWSER_HEADLESS: true
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0

heroku:
  HOST: "shopfortms.herokuapp.com"
  MODE_DEBUG: false
  REQUEST_TTL: 10
  VENV_SYNTHETIC: true